### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eedahl** [mrkkrp/fix-input#2]
Hi,

I'm on a Norwegian keyboard layout but would like to use a US-style overlay for it such that, e.g., å corresponds to the command tied to { on a US keyboard (go to beginning of paragraph in evil mode), because they're in the same place on the keyboard. It looks like that's what this package is supposed to let me do, but it's not totally clear to me from the documentation. Am I on the right track? :)

- Eivind

**Comment by mrkkrp** [comment]
OK, you need something like this:

``` emacs-lisp
(fix-input "norwegian-keyboard" ;; or "norwegian-postfix", I don't know
           nil         ;; need “default” US input method here
           "new-input-method")
```

There is a problem with “default” US input method, it does not seem to exist because it's well, default. You can try various `latin-*` things or define such input method on your own, it should just map symbols to themselves, and then `fix-input` will reverse it for you so when you have Norwegian keyboard Emacs will work as if you have US layout.

Hope it helps, tell me if it works!

**Comment by eedahl** [comment]
Thanks! :) If you don't mind me asking: Is there any danger that I'll destroy anything? Should I then just remove the package and will that clean it up, or can I clean it up some other way?

**Comment by mrkkrp** [comment]
No, no danger. It just generates a new input method that you can the enable/disable. Also, it does so on the fly, so if you remove the `fix-input` invocation you'll be back to your original setup.

**Comment by eedahl** [comment]
That's amazing, thank you very much. I'll play around with it; should make my life with this new editor a lot easier.

**Comment by eedahl** [comment]
I guess a feature request would be a "us-qwerty-default" input method, haha

**Comment by mrkkrp** [comment]
Sorry, have no time to write actual elisp to help you, but try asking for such input method here:

https://emacs.stackexchange.com/

There will be people who can do it (it's pretty simple I guess when you have fresh memories about how input maps are represented).

**Comment by eedahl** [comment]
I'll try there! And if not, I have a small project to try if I get some spare time :)

**Comment by eedahl** [comment]
For future reference, I asked this question on emacs-se: https://emacs.stackexchange.com/questions/28610/default-us-input-method-for-use-with-fix-input

**Comment by mrkkrp** [comment]
I'm not sure if you have found a solution, but I think it's fair to close the issue now due to the lack of activity.
